### ISSUE TITLE
Add configuration

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/first-timers-bot#105]
see https://probot.github.io/probot/latest/Context.html#config. I think this will require a new permission to read-access `.github/first-timers.yml` in repositories.

Things that I would like to be able to configure

1. labels
2. template
3. repository where to create the issue

Point `3.` is for Hoodie specifically, as we have a dedicated repository where we want to create the issues for all repositories in the GitHub organisation.

Before working on that, we should have good tests for the existing code base first. And as these are new features, we should make sure to document them in the README and the description at https://github.com/apps/first-timers

**Comment by agonzalez0515** [comment]
What would users configure in the template?

**Comment by gr2m** [comment]
What will be an interesting challenge is that if I set a specific repository in which the issues shall be created, I’d like to load the template from this repository, too, instead of having template files in all the separate repositories where I install the app. So maybe we should optionally allow to set the `template` option to a URL?

**Comment by gr2m** [comment]
labels & repository is implemented, I’ll create a follow up issue for the template
