### ISSUE TITLE
rename app to just first-timers

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/first-timers-bot#120]
I think it’s fairly straight forward

- [x] create pull request to update https://probot.github.io/
- [x] update URL on the repository https://github.com/hoodiehq/first-timers-bot
- [x] rename the bot https://github.com/organizations/hoodiehq/settings/apps/first-timers-bot
- [x] merge the pull request from step 1

Bonus: create a new app with the name `first-timers-bot` and just add a description that it’s deprecated and that it now lives at https://github.com/apps/first-timers

**Comment by agonzalez0515** [comment]
closed by #121
