### ISSUE TITLE
💡 Add section about Hacktoberfest to template

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/first-timers-bot#134]
See this issue for an example: https://github.com/hoodiehq/camp/issues/82
Why not give Hacktoberfest a shout out :D

**Comment by gr2m** [comment]
@agonzalez0515 @Techforchange let’s turn this into a first timers issue :)

**Comment by daniel-234** [comment]
Hi @gr2m and @agonzalez0515, is this 'first timers issue' still open? I would like to claim it.

**Comment by gr2m** [comment]
@daniel-234 it was a misunderstanding, sorry. This is not a first-timers issue by itself, but it will be turned into one, which will then appear on https://github.com/hoodiehq/camp/issues

**Comment by gr2m** [comment]
@daniel-234 there it is: https://github.com/hoodiehq/camp/issues/129 there are lots of folks who want to work on these, we usually wait a day and then pick a person by random
