### ISSUE TITLE
link to changed file has commit sha instead of branch name in its URL

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/first-timers-bot#135]
for example in this issue: https://github.com/gr2m/initials/issues/32

the link behind `README.md` in step 3 linked to https://github.com/gr2m/initials/blob/d5bccfe96675007a562360bb2e2c48c4a50d7f92/README.md which doesn’t work, because in order for the edit button to work, the link must use a branch name instead. The correct link is https://github.com/gr2m/initials/blob/master/README.md

**Comment by Techforchange** [comment]
Claiming this :)

**Comment by RaiVaibhav** [comment]
Sir i did't get problem does i have to change the link???i did't get it or its is a tutorial

**Comment by RaiVaibhav** [comment]
@Techforchange i am new so new idea

**Comment by Techforchange** [comment]
@RaiVaibhav No worries! I'm currently working on this issue but feel free to grab one of the other issues. All your help is greatly appreciated :) Let me know if you have any questions!

**Comment by RaiVaibhav** [comment]
Ok No Problem But what exactly we have to do here @Techforchange i did't understand the question

**Comment by RaiVaibhav** [comment]
@gr2m can you please help?

**Comment by gr2m** [comment]
@RaiVaibhav did you get here via  gr2m/initials#32? This is an entirely different project here :) 

This issue is not a good first issue to work on if you don’t yet know how first-timers-bot works. There are other issues that are better suited

**Comment by RaiVaibhav** [comment]
@gr2m Yes i go through the link https://github.com/gr2m/initials/issues/32, and i also get that we have to change the link of readme.md as edit button will not work , i have taken it in wrong sense like edit in documentation soory my bad

**Comment by RaiVaibhav** [comment]
ok  i got it whoever is claiming have to solve the issue and we have to change the link of bot 
Thanks @gr2m  for helping me
