### ISSUE TITLE
Travis: avoid double builds

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/first-timers-bot#147]
see https://github.com/semantic-release/release-notes-generator/blob/370fd6eed8ebfd8b8b1358ef258835f7cf3e1f56/.travis.yml#L5-L10 for comparison

**Comment by arlene-perez** [comment]
WIP :)

**Comment by Techforchange** [comment]
WIP :)

**Comment by gr2m** [comment]
we no longer use travis :)
