### ISSUE TITLE
Clarify configuration of template & repository

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/first-timers-bot#150]
when both template & repository is set, then the template is loaded from the configured repository at the configured template path.

I think we should also change the order of the documented configuration, sorted by how likely the configuration is being used. I _think_ the order should be 

1. labels
2. template
3. repository

**Comment by Techforchange** [comment]
https://github.com/hoodiehq/first-timers-bot/pull/151 Done :)

**Comment by gr2m** [comment]
have you seen my comment at https://github.com/hoodiehq/first-timers-bot/pull/151#discussion_r144703515?

**Comment by gr2m** [comment]
done via #151
