### ISSUE TITLE
don’t add the commit body text to issue subject

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/first-timers-bot#152]
it currently puts both the commit subject and body into the issue subject. I’ve fixed it now on the issue

![image](https://user-images.githubusercontent.com/39992/31578778-ec52e06e-b0dc-11e7-97db-ca185e3eabdb.png)

The issue is https://github.com/hoodiehq/camp/issues/126
The commit is https://github.com/hoodiehq/hoodie-account-server-api/commit/3a307578a8af71c69de1a7c7e882a43fe76aed58

We should instead make the issue body another placeholder in the template :)

**Comment by pathawks** [comment]
I wonder if the original committer could be added to the issue template as well. That would allow things like:

```test
Comments from $COMMITTER:
> $MESSAGE
```

**Comment by gr2m** [comment]
with "original committer" you mean the person who created the `first-timers-...` branch? I like the idea! What would the value of `$COMMITTER` be? Username? Name?

**Comment by pathawks** [comment]
Right, the person who created the branch.

The value of `$COMMITTER` should be that person’s GitHub username in the form `@pathawks`. This would cause the generated issue to appear in the list of issues I am mentioned in, and make it obvious who could answer any questions about the changes.

**Comment by gr2m** [comment]
we will call the variable `$AUTHOR` and it will be the commit author’s github username. Committer & author are two different things, the author refers to the person who made the commit. Someone else can be the committer, e.g. a maintainer squashed & merged a PR
