### ISSUE TITLE
add a placeholder for ISSUE_NUMBER

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/first-timers-bot#153]
It would be nice to know the current issue number, so we can explain that the person working on it can mention the issue in their pull request to automatically close it. We currently have that in the template for hoodiehq/camp, it says `Mention closes hoodiehq/camp#THIS_ISSUE_NUMBER in the description`. It would be nice to be able to replace `THIS_ISSUE_NUMBER` with the actual issue number

For that to work, we need to create the issue first, and then update the issue afterwards. We only need to do that if the template has the `${ISSUE_NUMBER}` placeholder

**Comment by iuliaav** [comment]
May I try my hand on this issue? :)

**Comment by gr2m** [comment]
absolutely :) Let us know if you have any questions!

**Comment by gr2m** [comment]
@synicalsyntax @charmaine would you like to take on this issue?
