### ISSUE TITLE
question re: "Accept our invitation" line

### ISSUE THREAD

**Issue by lmccart** [hoodiehq/first-timers-bot#154]
This is awesome! I'm a little confused by this line:
```
 Accept our invitation to this repository. Once accepted, assign yourself to this repository
```
By invite to repository, does that mean they get added as collaborator? (I assume so)
Once added, what does it mean for them to assign themselves to the repo? Or should this last word be "issue"?

Thanks!

**Comment by gr2m** [comment]
Oh thanks, yes the word should be "issue". Could you send a pull request to fix that?

> By invite to repository, does that mean they get added as collaborator?

Yes, we extracted the process from how we do issues at Hoodie. We have a dedicated repository for the first-time contributors, inviting them to this repository has no risk to us. But now that you mention it, I wonder if that is a good default for other users of the app 🤔
