### ISSUE TITLE
Add Uptimerobot to read me

### ISSUE THREAD

**Issue by Techforchange** [hoodiehq/first-timers-bot#160]
Update read me file with https://stats.uptimerobot.com/LZ40Lcoj4 for stats on server

**Comment by gr2m** [comment]
Oh turns out there is a badge, thanks to shields.io! 

[![Uptime Robot status](https://img.shields.io/uptimerobot/status/m779426128-6b6e81ed8dc987db17d4cad2.svg)](https://stats.uptimerobot.com/LZ40Lcoj4)

Here is the markdown for the badge:

```markdown
[![Uptime Robot status](https://img.shields.io/uptimerobot/status/m779426128-6b6e81ed8dc987db17d4cad2.svg)](https://stats.uptimerobot.com/LZ40Lcoj4)
```

**Comment by Techforchange** [comment]
https://github.com/hoodiehq/first-timers-bot/pull/167

**Comment by gr2m** [comment]
done via #167
