### ISSUE TITLE
What exactly step 2 is talking about?

### ISSUE THREAD

**Issue by rasad74** [hoodiehq/first-timers-bot#200]
Hi,

Newbie here and wondering what is step 2 talking about? Do I need to clone the repository and then create a config.yml in it?

![image](https://user-images.githubusercontent.com/31104236/43547058-c79f4b74-959f-11e8-8f6a-efbaecf684bb.png)

**Comment by gr2m** [comment]
you don’t need to clone the repository, just create the config.yml file in the repository that you want to install the first timers app on. Note that this is for github.com, i’m not sure how it works on self-hosted GitHub Enterprise at this point
