### ISSUE TITLE
Optionally checking if the Pull Request contains the changes requested

### ISSUE THREAD

**Issue by alexanmtz** [hoodiehq/first-timers-bot#208]
Great app! I'm using on my project [https://gitpay.me](https://gitpay.me) for issues like and I was wondering if would be cool feature that would check if the PR contains the changes. In other words, if the commits related to that Pull Request fits with the hidden branch change.

**Comment by gr2m** [comment]
That would be a cool experiment! There might be false negatives as sometimes the changes might not be identical but still acceptable to fix the respective issue. But would love to see what you come up with

**Comment by alexanmtz** [comment]
@gr2m Actually I found a great tool created by Github that will do that in a really effective and interactive way:
https://github.com/marketplace/github-learning-lab

I think we can close this.
