### ISSUE TITLE
Not working recently on installed repository?

### ISSUE THREAD

**Issue by jywarren** [hoodiehq/first-timers-bot#233]
Hi, reopening this as FTB hasn't been running for us recently. Continuing from possibly related  #212 -- 

I followed your advice to check the logs, and found:

https://zeit.co/first-timers-bot/first-timers-bot/tvczmldkah

```
2020-01-09T17:12:23.749Z probot:first-timers:publiclab/plots2 webhook received for branch "first-timers-authors-tooltip"
--
Jan 09 2020 12:12:23:8832020-01-09T17:12:23.749Z probot:first-timers:publiclab/plots2 getting branch "first-timers-authors-tooltip"
Jan 09 2020 12:12:24:1792020-01-09T17:12:24.099Z probot:first-timers:publiclab/plots2 "first-timers-authors-tooltip" branch found, last commit’s sha: a66f3f2d7e8da1ac6c906c65c7baee08ddf00e0a
Jan 09 2020 12:12:24:6542020-01-09T17:12:24.585Z probot:first-timers:publiclab/plots2 getting commit "a66f3f2d7e8da1ac6c906c65c7baee08ddf00e0a"
Jan 09 2020 12:12:24:704{ Deprecation: [@octokit/rest] "sha" parameter is deprecated for ".repos.getCommit()". Use "commit_sha" instead
Jan 09 2020 12:12:24:760    at Object.keys.forEach.key (/home/nowuser/src/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:71:26)
Jan 09 2020 12:12:24:980    at Array.forEach (<anonymous>)
Jan 09 2020 12:12:25:070    at Object.patchedMethod [as getCommit] (/home/nowuser/src/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:67:26)
Jan 09 2020 12:12:25:071    at getCommit (/home/nowuser/src/lib/get-commit.js:6:26)
Jan 09 2020 12:12:25:072    at <anonymous> name: 'Deprecation' }
Jan 09 2020 12:12:25:0742020-01-09T17:12:24.605Z probot:first-timers:publiclab/plots2 HttpError: Empty value for parameter 'ref': undefined
```

Especially `Jan 09 2020 12:12:25:0742020-01-09T17:12:24.605Z probot:first-timers:publiclab/plots2 HttpError: Empty value for parameter 'ref': undefined` -- do you know what that means? Does it relate to HTML in our project, like a `ref` HTML tag attribute that's empty?

It's for the branch in this PR: https://github.com/publiclab/plots2/pull/7160

**Comment by gr2m** [comment]
Hi @jywarren 👋 happy new year!

The empty value for `ref` might indeed be a (or the) problem. Let me have a look into it

**Comment by gr2m** [comment]
Hm I'm seeing a different error now: 

> HttpError: Empty value for parameter 'issue_number': undefined

looking into it

**Comment by gr2m** [comment]
Issue was created though: https://github.com/gr2m/sandbox/issues/96

**Comment by gr2m** [comment]
should be fixed via 469bb75. This fixes the request that replaces the `$ISSUE_NUMBER` placeholder after the issue was created.

**Comment by gr2m** [comment]
Yep, works all as expected now:
https://github.com/gr2m/sandbox/issues/97

**Comment by jywarren** [comment]
Thank you so much for your response and swift fix! Happy new year indeed!
