### ISSUE TITLE
New issue not created

### ISSUE THREAD

**Issue by jywarren** [hoodiehq/first-timers-bot#272]
Hi, I recently tried opening a new FTO from the branch this PR is based on https://github.com/publiclab/plots2/pull/8748 (i just created the PR to help aggregate the troubleshooting in) but the issue didn't open. 

Building on steps from https://github.com/hoodiehq/first-timers-bot/issues/233 and https://github.com/hoodiehq/first-timers-bot/issues/212 I tried looking up the logs:

https://zeit.co/first-timers-bot/first-timers-bot/tvczmldkah, https://zeit.co/deployments/first-timers-bot.now.sh/logs

I wasn't able to access them w my GitHub account. I wonder if you might have a moment to look up the issue? Thank you so much!!! Hope you are well!

**Comment by gr2m** [comment]
we no longer host the app on vercel, because Vercel no longer supports deploying long-running processes that the current probot requires (but we are working to make probot work with serverless environments right now).

We currently host it on heroku, let me see if I find anything in the logs

**Comment by jywarren** [comment]
OK, thanks, and hi @gr2m -- so fast with the responses as always 😄 ❤️ 

Nothing urgent on our end in case that's helpful!

**Comment by gr2m** [comment]
I was able to reproduce the problem, looking into it

**Comment by gr2m** [comment]
Looks like it we got bitten by https://github.com/probot/probot/issues/1394, or a related problem. Updating to the latest probot fixed it. Can you try again please?

**Comment by gr2m** [comment]
I've also setup error reporting with sentry, so I should get notified in future if things blow up again

**Comment by jywarren** [comment]
Great, thank you! We use Sentry too - it's great! All resolved -- see https://github.com/publiclab/plots2/issues/8749 for a newly created one. Thanks again @gr2m !!!!!
