### ISSUE TITLE
README: Add "about" section

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/first-timers-bot#85]
You should definitely let the world know who you are and how people can find out more about your work. I think the way how the bot became to be is pretty cool, too! :)

**Comment by Techforchange** [comment]
Good point! Will work on this next week :) @agonzalez0515 @gr2m

**Comment by agonzalez0515** [comment]
Pull request #106 
Will probably want to add a little more to the section but I just wanted to have something there for now.
