### ISSUE TITLE
Need a First-timers-bot avatar

### ISSUE THREAD

**Issue by agonzalez0515** [hoodiehq/first-timers-bot#93]
We're looking for someone to contribute their amazing design skills to our project by creating an avatar.  We were thinking something like a robot wearing a hoodie? We're open to suggestions!

https://github.com/apps/first-timers-bot

**Comment by michaelmccombie** [comment]
I took a look at a couple of Github apps and it looks like Github doesn't let you use the entire 56px by 56px space for the avatar image. It restricts you to a 24 x24 image space surrounded by 16px of padding. I'll tweak that original image and post it again here
 
![image](https://user-images.githubusercontent.com/5924575/30197961-149ceb84-9420-11e7-930b-fad5f24a1a3e.png)

**Comment by michaelmccombie** [comment]
Here's a V2 with the new constraints in mind
![image](https://user-images.githubusercontent.com/5924575/30198526-065f3b82-9423-11e7-8b31-c584bb2e2b63.png)

**Comment by michaelmccombie** [comment]
![avatar](https://user-images.githubusercontent.com/5924575/30198679-c1f36256-9423-11e7-886b-d3dbe8d14b5d.png)

**Comment by agonzalez0515** [comment]
Thanks Michael! I'm going to discuss with my pair and let you know. I think we might ask for some color changes, probably a pink hoodie, but I'll get back to you on the exact shade.

Also, when we credit you on the readme, where would you like that to link to?

**Comment by michaelmccombie** [comment]
Open to any changes! A pink hoodie sounds like a good idea to me! 

You can just link to my twitter account https://twitter.com/michaelbuilds on the ReadMe

**Comment by agonzalez0515** [comment]
can we see it wearing a pink hoodie? Something along this color :two_hearts: ?

**Comment by michaelmccombie** [comment]
![avatar](https://user-images.githubusercontent.com/5924575/30228919-aac6fe6e-9494-11e7-9794-f35f64be16ed.png)

**Comment by michaelmccombie** [comment]
![image](https://user-images.githubusercontent.com/5924575/30228992-f2f673cc-9494-11e7-9cae-99f55aaee59b.png)

**Comment by agonzalez0515** [comment]
thoughts? @Techforchange @gr2m

**Comment by gr2m** [comment]
💞 😻💓

**Comment by agonzalez0515** [comment]
@michaelmccombie yess thank you! Can you please submit a PR with the image file and the source file? This way we can resize or add something if need to. You can add it to our assets folder.  Again, thank you!!!

**Comment by michaelmccombie** [comment]
I tried creating a new branch and then publishing the branch but ran in to this error 
![image](https://user-images.githubusercontent.com/5924575/30234416-c2332c18-94b1-11e7-89eb-6dcd96057775.png)

**Comment by gr2m** [comment]
hmm I’ve never seen that error before. You might need to fork the repository first. Let me know if you need any guidance :)

**Comment by michaelmccombie** [comment]
Sorry about the delay. Still wasn't able to figure out the how to get around the permissions issue. So I created a publicly available folder in Dropbox that someone can grab the files from. Includes a Sketch file (original file), an SVG file (you should be able to pull that into Photoshop/ Illustrator/ Figma/ Any text editor if you need to update something), and a PNG the same size as the Github apps.

https://www.dropbox.com/sh/yco0wzkoef3sq98/AACDPLCaFpsu8FShVwaamjr2a?dl=0

**Comment by agonzalez0515** [comment]
Thank you Michael!!
