### ISSUE TITLE
template: remove the steps for Code of Conduct and changing labels

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/first-timers-bot#95]
the Code of Conduct link does currently point to http://hood.ie/code-of-conduct/ which does not apply to other projects. I would suggest you leave it out for now and make a follow up issue to check if the repository has a code of conduct file and if it does, then show it, otherwise, don’t.

The labels mentioned are also specific to Hoodie, I would leave out these steps for now. Maybe make also a follow up issue for this, but let’s see how people will end up using it, I’m sure there will be some cool feedback coming in soon :)

**Comment by gr2m** [comment]
Oh, same with the last section: `🤔❓ Questions` – I would suggest to remove the links in there and just say people shall comment below if they have any, something generic that would fit for any project.

**Comment by agonzalez0515** [comment]
closed by #110
